import fs from 'fs';

const openapi = JSON.parse(
  fs.readFileSync('./src/lib/api/openapi/auth/auth.api.docs.json', 'utf-8')
);

function refToType(ref) {
  return ref ? ref.split('/').pop() : null;
}
let output = `// this was generated by a script do not change \n`;
output += `import { defineRoute } from './defineRoutes.js';\n`;
output += `import {\n`;
const allSchemas = new Set();

// Collect routes
const routes = [];

for (const [path, methods] of Object.entries(openapi.paths)) {
  for (const [method, op] of Object.entries(methods)) {
    const key = op.operationId;
    const description = op.summary || '';
    const auth = op.security ? op.security.flatMap((s) => Object.keys(s)) : [];
    const ttl = op['x-ttl'];
    const timeout = op['x-timeout'];
    const enabled = op['x-enabled'] ?? true;

    const reqBody = refToType(
      op.requestBody?.content?.['application/json']?.schema?.$ref
    );

    const responses = {};
    for (const [status, resp] of Object.entries(op.responses || {})) {
      const schema = refToType(
        resp.content?.['application/json']?.schema?.$ref
      );
      if (schema) responses[status] = schema;
    }

    const allRefs = [reqBody, ...Object.values(responses)].filter(Boolean);
    allRefs.forEach((r) => allSchemas.add(r));

    routes.push({
      key,
      path,
      method: method.toUpperCase(),
      description,
      auth,
      schemas: { body: reqBody, responses },
      meta: { ttl, timeout, enabled },
    });
  }
}

// Generate import block
output += `  ${[...allSchemas].join(',\n  ')}\n`;
output += `} from './DTO/index.js';\n\n`;

output += `// this was generated by a script do not change \n`;
output += `export const routes = {\n`;
for (const route of routes) {
  output += `  '${route.key}': defineRoute({\n`;
  output += `    key: '${route.key}',\n`;
  output += `    path: '${route.path}',\n`;
  output += `    method: '${route.method}',\n`;
  if (route.description) output += `    description: '${route.description}',\n`;
  if (route.auth.length) output += `    auth: ${JSON.stringify(route.auth)},\n`;
  output += `    meta: ${JSON.stringify(route.meta, null, 6)},\n`;
  output += `    schemas: {\n`;
  if (route.schemas.body) output += `      body: ${route.schemas.body},\n`;
  output += `      responses: {\n`;
  for (const [status, type] of Object.entries(route.schemas.responses)) {
    output += `        ${status}: ${type},\n`;
  }
  output += `      },\n`;
  output += `    },\n`;
  output += `  }),\n`;
}

output += `} as const;\n`;

fs.writeFileSync('./src/lib/api/generated-routes.ts', output);

console.log('✅ Generated routes.generated.ts');
