// this was generated by a script do not change 
import { defineRoute } from './defineRoutes.js';
import {
  OAuthCreateEmailRequestDTO,
  OAuthCreateEmailResponseDTO,
  ApiErrorSchema,
  AuthCreateEmailRequestDTO,
  AuthCreateEmailResponseDTO
} from './DTO/index.js';

// this was generated by a script do not change 
export const routes = {
  'auth:create:withOauth2': defineRoute({
    key: 'auth:create:withOauth2',
    path: '/auth/google',
    method: 'POST',
    description: 'Create a new user with OAuth2',
    auth: ["admin"],
    meta: {
      "ttl": 30,
      "enabled": true
},
    schemas: {
      body: OAuthCreateEmailRequestDTO,
      responses: {
        201: OAuthCreateEmailResponseDTO,
        400: ApiErrorSchema,
      },
    },
  }),
  'auth:create:withGithubOauth2': defineRoute({
    key: 'auth:create:withGithubOauth2',
    path: '/auth/github',
    method: 'POST',
    description: 'Create a new user with GitHub OAuth2',
    auth: ["admin"],
    meta: {
      "ttl": 30,
      "enabled": true
},
    schemas: {
      body: OAuthCreateEmailRequestDTO,
      responses: {
        201: OAuthCreateEmailResponseDTO,
        400: ApiErrorSchema,
      },
    },
  }),
  'auth:create:withEmail': defineRoute({
    key: 'auth:create:withEmail',
    path: '/auth/email',
    method: 'POST',
    auth: ["admin"],
    meta: {
      "enabled": true
},
    schemas: {
      body: AuthCreateEmailRequestDTO,
      responses: {
        201: AuthCreateEmailResponseDTO,
        400: ApiErrorSchema,
      },
    },
  }),
} as const;
